services:
  rviz:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ipc: host
    pid: host
    runtime: nvidia
    volumes:
      - type: bind
        source: /home/${USER}/ros2_ws
        target: /ros2_ws
      - type: bind
        source: /home/${USER}/repos/humble-docker
        target: /repos/humble-docker
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./rosbot_pro.rviz:/root/.rviz2/default.rviz
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: bash
